### ISSUE TITLE
Manually allow for hiding a selected element

### ISSUE THREAD

**Issue by xcoulon** [jbosstools/jbosstools-playground#18]
Here's my use-case: I have some files/folders/elements that I don't need to see in my workspace (even something like the "JRE System Library" of a parent Maven project). I'd like to have the possibility to manually select those elements in the project explorer and have a "hide" command somewhere to hide them (with a mean to restore them in the view).

**Comment by mickaelistria** [comment]
Closing here. This should be tracked upstream at Eclipse.
