### ISSUE TITLE
[Nestor] Show in... > Project Explorer does not work

### ISSUE THREAD

**Issue by ppalaga** [jbosstools/jbosstools-playground#20]
Show in... > Project Explorer does not work when called from a context menu of an Editor or Outline.

Steps to reproduce:
(1) Have nested modules enabled in Project Explorer
(2) Open a java file. I am not sure if it is important whether the files comes from a nested project. But I find this highly probable
(3) Invoke `Show in... > Project Explorer` from a context menu of the Java Editor or from the outline Outline.

Expected: Project Explorer is focused and the file is revealed therein.

Found: Project Explorer is focused but the file is not revealed therein.

**Comment by mickaelistria** [comment]
Nested view of projects has been moved to Eclipse Platform UI, latest nightly build and next integration builds should include it.
Please report issues on bugs.eclipse.org now, project "Eclipse" component "UI".
