### ISSUE TITLE
updates site does not longer work

### ISSUE THREAD

**Issue by maxandersen** [jbosstools/jbosstools-playground#33]
shows up with p2 remediation ui and complains about missing e4 bundles.

**Comment by maxandersen** [comment]
Cannot complete the install because one or more required items could not be found.
  Software being installed: EGit wizard delegating import to Easymport 1.0.0.Alpha2-v20150226-1025-B31 (org.jboss.tools.playground.easymport.egit 1.0.0.Alpha2-v20150226-1025-B31)
  Missing requirement: EGit wizard delegating import to Easymport 1.0.0.Alpha2-v20150226-1025-B31 (org.jboss.tools.playground.easymport.egit 1.0.0.Alpha2-v20150226-1025-B31) requires 'bundle org.eclipse.e4.ui.importer 0.1.0' but it could not be found

**Comment by mickaelistria** [comment]
Since most have moved to Eclipse Platform, the content of the site can now be installed against Neon M7.
